apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mealie
    files:
      - env_vars

images:
  - name: mealie
    newName: ghcr.io/mealie-recipes/mealie
    newTag: v3.0.1

labels:
  - pairs:
      app.kubernetes.io/name: mealie
      app.kubernetes.io/version: v2
    includeSelectors: false
  - pairs:
      app.kubernetes.io/instance: mealie
    includeSelectors: true

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

