apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mealie
    files:
      - env_vars

labels:
  - pairs:
      app.kubernetes.io/name: mealie
      app.kubernetes.io/version: v2
    includeSelectors: false
  - pairs:
      app.kubernetes.io/instance: mealie
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

