democratic-csi:
  csiDriver:
    name: "iscsi"

  storageClasses:
    - name: iscsi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        fsType: ext4
        detachedVolumesFromSnapshots: "false"
      mountOptions: [ ]
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

  volumeSnapshotClasses: []
#    - name: iscsi
#      parameters:
#        detachedSnapshots: "true"

  driver:
    existingConfigSecret: "democratic-csi-driver-config"
    config:
      driver: freenas-api-iscsi
      instance_id:
      httpConnection:
        protocol: http
        host: 192.168.2.3
        port: 80
        allowInsecure: true

      zfs:
        datasetParentName: habbo/k8s/iscsi/v
        detachedSnapshotsDatasetParentName: habbo/k8s/iscsi/s
        zvolCompression:
        zvolDedup:
        zvolEnableReservation: false
        zvolBlocksize:

      iscsi:
        targetPortal: "192.168.2.3:3260"
        targetPortals: []
        interface:
        namePrefix: csi-
        nameSuffic: "-homelab"

        targetGroups:
          - targetGroupPortalGroup: 1
            targetGroupInitiatorGroup: 1
            targetGroupAuthType: None
            targetGroupAuthGroup:

        extentInsecureTpc: true
        extentXenCompat: false
        extentDisablePhysicalBlocksize: true
        # 512, 1024, 2048, or 4096,
        extentBlocksize: 512
        # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
        extentRpm: "SSD"
        # 0-100 (0 == ignore)
        extentAvailThreshold: 0

  node:
    hostPID: true
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /var/iscsi
      iscsiDirHostPathType: ""


