traefik:
  ports:
    websecure:
      tls:
        enabled: true
        certResolver: "letsencrypt"

  ingressRoute:
    dashboard:
      enabled: true

  certificatesResolvers:
    letsencrypt:
      acme:
        caServer: "https://acme-v02.api.letsencrypt.org/directory"
        email: info@rcomanne.nl
        tlsChallenge: { }
        storage: /data/letsencrypt.json

  providers:
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: true
    kubernetesCRD:
      enabled: true

  logs:
    general:
      format: json
      level: INFO