ports:
  traefik:
    expose: true
  websecure:
    tls:
      enabled: true
      certResolver: "letsencrypt"

ingressRoute:
  dashboard:
    enabled: true

certResolvers:
  letsencrypt:
    caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: info@rcomanne.nl
    tlsChallenge: true
    storage: /data/letsencrypt.json

providers:
  kubernetesIngress:
    allowExternalNameServices: true
    publishedService:
      enabled: true

logs:
  general:
    format: json
    level: INFO