traefik:
  ports:
    websecure:
      tls:
        enabled: true
        certResolver: "letsencrypt"

  ingressRoute:
    dashboard:
      enabled: true

  certificatesResolvers:
    letsencrypt:
      acme:
#        caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" # STAGING
        caServer: "https://acme-v02.api.letsencrypt.org/directory" # PROD
        email: info@rcomanne.nl
        tlsChallenge: true
#        httpChallenge:
#          entryPoint: web
        storage: /data/letsencrypt.json

  providers:
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: true
    kubernetesCRD:
      enabled: true

  logs:
    general:
      format: json
      level: DEBUG