home-assistant:
  controller:
    type: StatefulSet

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: iscsi

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: home-assistant.rcomanne.nl
        paths:
          - path: /
            pathType: Prefix

  configuration:
    enabled: true