#!/bin/bash
set -eo pipefail

read -rp "Control plane IP address = " control_plane_ip

echo 'Generating configurations'
talosctl gen config talos-vbox-cluster "https://${control_plane_ip}:6443" --output-dir .out

echo 'Creating control plane node'
talosctl apply-config --insecure --nodes ${control_plane_ip} --file .out/controlplane.yaml

echo 'Startup the worker nodes and wait for the master to be ready to accept workers'
read -rp "Worker node(s) IP address(es) = " worker_ips

echo 'Creating worker node(s)'
ifs=$IFS
IFS=,
for worker in ${worker_ips}; do
  echo "Creating worker node [${worker}]"
  talosctl apply-config --insecure --nodes ${worker} --file .out/worker_${worker}.yaml
done
IFS=$ifs
echo 'Starting bootstrapping process'
export TALOSCONFIG='.out/talosconfig'
talosctl config endpoint ${control_plane_ip}
talosctl config node ${control_plane_ip}

echo 'Bootstrapping etc'
talosctl service apid status
talosctl bootstrap

# Wait for the cluster to become healthy
i=0
while [ $i -le 5 ]; do
  echo "Checking cluster health try nr. ${i}"
  talosctl health --wait-timeout 30s
  ((i++))
done

echo 'Retrieving kubeconfig'
talosctl kubeconfig .

echo 'Configuring kubectl for the created kubeconfig'
cp kubeconfig ~/.kube/homelab
export KUBECONFIG="~/.kube/homelab"
